#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.001 >> nohup1.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.01 >> nohup2.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.1 >> nohup3.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=1 >> nohup4.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=10 >> nohup5.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=100 >> nohup6.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=1000 >> nohup7.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.05 >> nohup8.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.15 >> nohup9.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.2 >> nohup10.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.25 >> nohup11.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.3 >> nohup12.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.35 >> nohup13.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.4 >> nohup14.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.45 >> nohup15.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.5 >> nohup16.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.02 >> nohup1.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.04 >> nohup2.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.06 >> nohup3.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.08 >> nohup4.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.1 >> nohup5.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.05 >> nohup1.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.054 >> nohup2.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.058 >> nohup3.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.062 >> nohup4.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.066 >> nohup5.out 2>&1&
#nohup ./energy_test data/trunc_sample1.txt data/trunc_sample2.txt --n-permutations=200 --delta-value=0.07 >> nohup6.out 2>&1&

